"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

export default function JoinXoomsharePage() {
  const router = useRouter();
  const [pathCode, setPathCode] = useState("");
  const [error, setError] = useState("");

  const handleJoin = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const trimmedCode = pathCode.trim();
    if (!trimmedCode) {
      setError("Enter a secret page code");
      return;
    }

    router.push(`/${encodeURIComponent(trimmedCode)}`);
  };

  return (
    <main className="min-h-screen w-full bg-black font-inter text-white">
      <Link
        href="/xoomshare"
        className="absolute left-6 top-6 flex h-11 w-11 items-center justify-center rounded-full border border-white/10 bg-white/5 text-white transition-colors hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-white/40"
        aria-label="Back to create Xoomshare"
      >
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true">
          <path d="M15 6 9 12l6 6" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </Link>
      <div className="flex min-h-screen items-center justify-center px-6">
        <form onSubmit={handleJoin} className="flex w-full max-w-[320px] flex-col items-center">
          <label
            htmlFor="xoomshare-join-code"
            className="mb-8 w-[210px] text-center text-[13px] font-bold leading-[16px] text-white"
          >
            Enter secret page code generated by other device to continue
          </label>

          <div className="flex w-full items-end gap-4">
            <input
              id="xoomshare-join-code"
              value={pathCode}
              onChange={(event) => {
                setPathCode(event.target.value);
                setError("");
              }}
              autoFocus
              spellCheck={false}
              className="h-12 min-w-0 flex-1 border-0 border-b border-white/70 bg-transparent px-0 text-center text-[18px] font-bold leading-none text-white outline-none transition-colors placeholder:text-white/30 focus:border-white"
              aria-label="Secret page code"
            />
            <button
              type="submit"
              className="mb-3 flex h-8 w-8 shrink-0 items-center justify-center border-none bg-transparent text-white transition-opacity hover:opacity-80"
              aria-label="Join Xoomshare page"
            >
              <svg width="22" height="22" viewBox="0 0 16 16" fill="none" aria-hidden="true">
                <path d="M4.75 7V5.4a3.25 3.25 0 0 1 6.5 0V7M3.75 7h8.5v6.25h-8.5V7Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </button>
          </div>

          <p className="mt-6 text-[12px] font-bold leading-[15px] text-white">
            NOTE: Case Sensitive
          </p>

          {error && (
            <p className="mt-5 w-full text-center text-[12px] font-medium leading-[16px] text-red-300">
              {error}
            </p>
          )}
        </form>
      </div>
    </main>
  );
}
